# Generated by 'nixos-generate-config', then edited by hand to add the
# btrfs mount options that generate-config does not capture.
# The /boot UUID was corrected from C69A-DF66 to CB75-F43F after install.
{ config, lib, pkgs, modulesPath, ... }:

let
  btrfsOpts = [ "compress=zstd:1" "noatime" "ssd" "discard=async" ];
  disk = "/dev/disk/by-uuid/75f1dc79-d437-47b2-ad47-98aadd3c3221";
in
{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = disk;
      fsType = "btrfs";
      options = [ "subvol=@" ] ++ btrfsOpts;
    };

  fileSystems."/home" =
    { device = disk;
      fsType = "btrfs";
      options = [ "subvol=@home" ] ++ btrfsOpts;
    };

  fileSystems."/nix" =
    { device = disk;
      fsType = "btrfs";
      options = [ "subvol=@nix" ] ++ btrfsOpts;
      neededForBoot = true;
    };

  fileSystems."/var/log" =
    { device = disk;
      fsType = "btrfs";
      options = [ "subvol=@log" ] ++ btrfsOpts;
      neededForBoot = true;
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/CB75-F43F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
